name: Update latest user agents
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * MON'

jobs:
  build:
    name: Update latest user agents
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run black
        run: black .

      - name: Scrape UAs
        run: python main.py

      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages

      - name: Move build files to repo folder
        run: rsync -a --delete --exclude .git --exclude .nojekyll --exclude index.html build/ gh-pages/

      - name: Push repo changes
        run: |
          cd gh-pages
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Update user agents"
            git push
          else
            echo "No changes to commit"
          fi
